#include<stdio.h>
#include<sys/msg.h>
#include<unistd.h>

int crear_cmsj()
{
	int msgid;
	msgid=msgget(0xA,IPC_CREAT|IPC_EXCL|0666);
	printf("msgid=%d\n",msgid);
}
/*
IPCS
MEMORIA COMPARTIDA-SOLO PARA COMUNICACION
SEMAFOROD-SINCRONIZACION
COLA DE MENSAJES-AMBOS
PARECIDA PIPES Y FIFOS(LIMITE FINITO, EL QUE ENVIO TIENE QUE EJECUTAR MSGSEND.
SI QUIERE PONER EL MSG EN UNA COLA LLENA-->BLOCK
MSGSND(4 ARGUMENTO, IPC_NOWAIT)->SI EL PROC QUIERE METER MENSAJE EN COLA Y COLA LLENA NO SE BLOCK.
*/
